### ISSUE TITLE
`@farfetched/core` is not added to default factories of `effector/babel-plugin`

### ISSUE THREAD

**Issue by mufasa71** [igorkamyshev/farfetched#233]
AFAIK SID is not needed for non-SSR applications which are working in browser only. 
<img width="473" alt="Screenshot 2022-12-30 at 20 22 24" src="https://user-images.githubusercontent.com/626420/210086158-f23d69d1-8293-4069-b48b-d87c743ce9f8.png">

1. Why we need to use `effector/babel-plugin` for non-ssr apps? Can we avoid using sids for caching? Maybe providing some mechanism to provide identifiers manually or automatically. maybe by using `name` like in `react-query`?
2. Even with babel plugin its not working properly i don't know why, but this line expects `|` delimiter? Which is not working properly without specifying  `factories: ["@farfetched/core"]` inside babel. https://github.com/igorkamyshev/farfetched/blob/master/packages/core/src/cache/key/key.ts#L79

**Comment by igorkamyshev** [comment]
Hello! Please excuse me for the waiting, it is kind of holiday for me.

Thanks for your questions, let me answer it:

1. `sid` is more convenient to unique identity of a _Query_ because it is really hard to validate that `name` fields of different _Query_ are unique across the application. Especially if because we can delegate this job to babel (or SWC). However, I assume it would be nice to provide a fallback on manually created names. It would be done in the next release. https://github.com/igorkamyshev/farfetched/issues/238
2. In old versions of Effector (before [22.4.0](https://github.com/effector/effector/releases/tag/effector%4022.4.0)) `@farfetched/core` was not included in `factories` by default, so I guess you should just upgrade `effector` package.

**Comment by mufasa71** [comment]
Thanks,

1. Cool, nice option 👍 
2. Its added only in `importName` for regular sids. I created simple reproduction [sandbox](https://codesandbox.io/s/crazy-ritchie-yg953e?file=/src/index.test.js). Its still not working without explicitly set `factories: ['@farfetched/core']` . I assume it fails due to this line  https://github.com/igorkamyshev/farfetched/blob/master/packages/core/src/cache/key/key.ts#L79 expects delimiter `|`  which is only added with `factories` option to add unique prefix.

**Comment by igorkamyshev** [comment]
Thanks for repro, I'll fix it in Effector 🤗

**Comment by igorkamyshev** [comment]
Fixed in Effector 22.5.1 🫰
