### ISSUE TITLE
Incorrect type inference for query in update operator

### ISSUE THREAD

**Issue by limkaa4** [igorkamyshev/farfetched#251]
repl: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQRQK5pQCeANCulmgLJ4xbAQB2ZeYAJpXAL5wBmUEEHABEAAV4YovNDGQALNGwD0yaGmEAoDTCJg0cAAoQAzvAC8iDXGtxgbAFxxGeEACNCVmzGAwANmkdTKGBGAHNPa1cINiJAmGCwiLg8Y0IASQcnF3coDS4tHT04AHEZI1NjACU0Y0hGVLgLcpgAbQBdLVV6+EgK-EIiRvJMbH7iAB4ANwg7MlKYZqqautSAPgAKBCS5DEY2fyhHDGMiRmQ4dYBKRtXLG3uUJlM4dGMhjAB3DB8+GXl14RyGAwMDGexKJQAK2MTDAvgwyDQcggvjYhAAdIVgKo0ejVCAlL0YMZhJctA8bOgYHgoIwXjV0dCmFckvkuGTtLp9M00owfhYtvdvH4AnAgiFwvcojE4glJTYUulMs43B58pyigBBNhsZrVACOBFMAGEmLxgKEhoKbBw6I4eXyYHlOk94Bgdc0aHRvEwhqgRtRaPQmONtbqTDADUaYKbGObQmRmhtrdYdnsDkcTmcLkhbRhuNczLcUw8us9Xu8vj9pLI5ACgSCwRCmYw4QikSi0VBMbpsdE0HjBISIySyCWKdYQDJkZlhAYAPIAZQAKsISEkJ3BpbE4AApRfzgBy6PFYWAvCI6zzZM37PJE6pNLpr0ZMMYLPubI5rFtaHWROMMZSDuGwmCOD0Iy9YNmCSVwd3HGxjDwZBEWMMEcxAIMfWYOBDQGdkbhAzdrEfWkiOI+5XjwXwYEcFp0QYvDiHRKiaLITDvQYRgWJqaiYA6CjrHyW9WTyS4gA

**Comment by igorkamyshev** [comment]
Hello! Thanks for report.

1. First error in REPL exists because Query can be not executed before Mutation, so its state can be `null`. You have to handle this case.
<img width="566" alt="Screenshot 2023-02-01 at 12 48 29" src="https://user-images.githubusercontent.com/26767722/215953407-c94f8f61-74ca-4616-a6eb-fb719cb0570a.png">
2. If we fix it (e.g., by adding `?`), we'll face a second error which ephesis that Query can be in success state or in failure state during update, so you have to handle it as well.
