### ISSUE TITLE
Support array serialization using bracket representation in query params

### ISSUE THREAD

**Issue by slavanchikus** [igorkamyshev/farfetched#271]
If one field is array in query params or in query source, it will be nice to add an opportunity to represent array in query string like that `?foo[]=bar&foo[]=foo`

**Comment by igorkamyshev** [comment]
So, because of standard JS API `URLSearchParams` does not support this type of serialization, I've decided to provide an escape hatch for APIs that are not following the same principle.

Since v0.8.0 you can pass a string to the `query` field and serialize it whatever you want 🤗

Will be released in a couple of weeks.
