### ISSUE TITLE
Recipe about Query/Mutation with FormData

### ISSUE THREAD

**Issue by picassoq** [igorkamyshev/farfetched#324]
For several hours I tried to find an option to upload the file.
I looked for examples in the documentation - I did not find it.
Apparently there are nuances that I'm missing.

```js
const uploadFileQuery = createJsonMutation({
	params: declareParams<{ file: File }>(),
	request: {
		method: 'POST',
		url: 'xxxxxxxxx',
		body: ({ file }) => {
			const data = new FormData()
			data.append('file', file, file.name)
			return data
			// return Object.fromEntries(data)
		},
	},
})
```

**Comment by igorkamyshev** [comment]
Hello! Sorry for the late reply 😢

So, `createJsonQuery` and `createJsonMutation` are suitable only for JSON APIs. It assumes that API works only with pure JSON. Since FormData is not JSON, it is impossible to send FormData via `createJsonMutation`.

In your case, it would be better to use `createMutation` or create your own `createFormDataMutation` (check the [recipe about it](https://farfetched.pages.dev/recipes/custom_mutation.html)).

There is a short version of your code with some corrections:

```ts
const uploadFileMutation = createMutation({
  effect: createEffect(({ file }: { file: File }) => {
    const data = new FormData();
    data.append('file', file, file.name);
    
    await fetch('xxxxxxxxx', { body: data, method: 'POST' })
  })
})
```

**Comment by igorkamyshev** [comment]
Sorry, closed by missclick. Let me rename your issue and mark it as a documentation problem 😇

**Comment by picassoq** [comment]
Thanks, Igor!
Now it's clear

**Comment by igorkamyshev** [comment]
Done in https://github.com/igorkamyshev/farfetched/pull/428
