### ISSUE TITLE
Cloudflare workers Error: The 'credentials' field on 'RequestInitializerDict' is not implemented

### ISSUE THREAD

**Issue by Denllay** [igorkamyshev/farfetched#434]
Cloudflare workers [doesn't support](https://github.com/cloudflare/workers-sdk/issues/2514#issuecomment-1374875751) credentials property in fetch options.

**Comment by igorkamyshev** [comment]
Thanks for the report 🙏 I believe we should not change our code because it follows specification, and it has to be considered as a bug in Cloudflare Workers runtime. However, I think it could be some workaround, something like this:

```ts
import { fetchFx } from '@farfetched/core'

fetchFx.use((req) => {
  const cfReq = removeCredentialsFromRequest(req)
  return fetch(cfReq)
})
```

I'll investigate it and add the final solution to the documentation.
