### ISSUE TITLE
Query cloning

### ISSUE THREAD

**Issue by igorkamyshev** [igorkamyshev/farfetched#75]
Since we are going to recommend creating plenty of queries and uses it locally, we need to provide some way to clone Query.

## Proposed API

Let any Query has a method `__.clone` that will create a clone of the Query, but we won't allow using directly, because of AST-awared tools and problems with methods. We can add operator `clone` that will accept any Query and call its internal `clone` method.

API can changes 🤗

**Comment by dzhiriki** [comment]
In my case, I need to create clones for mutation. And it seems like for mutation is it better to have behavior similar to `attach` from `effector` itself.

For example, I can have a single file that contains API for some entity i.e. `someEntityQuery`, `updateEntityMutation`. 

But I want to call `updateEntityMutation` from different places. For example, I can have 2 different features, each can call `updateEntityMutation`. But I need some way to differentiate these calls:
```ts
// features.a.ts
sample({
  clock: updateClicked,
  target: updateEntityMutation.start,
})

sample({
  clock: updateEntityMutation.finished.failure.
  target: showError,
})

// features.b.ts
sample({
  clock: otherUpdateClicked,
  target: updateEntityMutation.start,
})

sample({
  clock: updateEntityMutation.finished.failure.
  target: showToast,
})
```
Without clone\attach, whenever I call mutation, both `sample` will trigger. But if there was an ability to `attach` a query I could do something like that:
```ts
const localEntityMutation = attach(updateEntityMutation);

sample({
  clock: updateClicked,
  target: localEntityMutation.start,
})

sample({
  clock: localEntityMutation.start.
  target: showError,
})

// features.b.ts
const localEntityMutation = attach(updateEntityMutation);
sample({
  clock: otherUpdateClicked,
  target: localEntityMutation.start,
})

sample({
  clock: localEntityMutation.finished.failure.
  target: showToast,
})
```

And if I use `update` operator I want that events from the original mutation will be called so my query will receive the update from mutation calls — this is the reason why I think that for mutations it is better to have `attach` instead of `clone`.
